development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: firm_dev
  pool: 5
  username: root
  password: 
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: firm_prod
  pool: 5
  username: root
  password: 
